application: pycashexdev
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '1d'

- url: /media
  static_dir: pycash/static
  
- url: /cron/.*
  script: djangoappengine.main.application
  login: admin
  
- url: /favicon.ico
  static_files: pycash/static/images/favicon.ico
  upload: pycash/static/images/favicon.ico

- url: /robots.txt
  static_files: pycash/static/robots.txt
  upload: pycash/static/robots.txt
  
- url: /(.*\.(gif|png|jpg))
  static_dir: pycash/static/images
  expiration: '1d'
  
- url: /.*
  script: djangoappengine.main.application
